### ISSUE TITLE
Use correct formatting for timestamps

### ISSUE THREAD

**Issue by j-pendlebury** [BBC-archive/psammead#1236]
**Is your feature request related to a problem? Please describe.**
Different services have different timestamps requirements. E.g. UK timestamp: dd/mm/yyyy | US timestamp: mm/dd/yyyy.

We should add support for different timestamp formats.

**Describe the solution you'd like**
Use moment's format option to format the timestamps per service.

**Describe alternatives you've considered**
Not using moment? 

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
[Timestamp Info Grid](https://www.dropbox.com/s/st883m5a8u9hi3a/WS%20Home%20Pages%20%28Live%29.xlsx?dl=0)
WSFRONTPGS-120

**Comment by j-pendlebury** [comment]
what's the best way of doing this? put a value in the config for the timestamp format or something else?

**Comment by ghost** [comment]
On the `Timestamp Grid` there is no mapping service to format mapping. Where should one get those?

**Comment by dr3** [comment]
>Different services have different timestamps requirements. E.g. UK timestamp: dd/mm/yyyy | US timestamp: mm/dd/yyyy.

We shouldnt need to worry about this. Moment has mapping for common date formats like [this](https://github.com/moment/moment/blob/develop/locale/en-gb.js#L17-L24) so assuming were using them correctly, formats like `dd/mm/yyyy vs mm/dd/yyyy` should be done automagically :)

**Comment by andrew-nowak** [comment]
@dr3 Does that mean that https://github.com/bbc/psammead/blob/bac074cda992ba3ba5510441125a648b176978e2/packages/containers/psammead-timestamp-container/src/timestampUtilities.js#L4 and/or https://github.com/bbc/simorgh/blob/a9f1abe672767217c8354bfd7014e7a1b16bcc07/src/app/containers/StoryPromo/index.jsx#L84 need to be changed to 'LLL' (or some other number of Ls) then? Because I would think they would override the 'LLL' formatting string

**Comment by dr3** [comment]
@aacn500 I think `D MMMM YYYY, HH:mm z` would need to become `LL, LT z` to get the correct order for every locale :)
