### ISSUE TITLE
Add 'LIVE' label to story promo for Live Page Promos

### ISSUE THREAD

**Issue by j-pendlebury** [BBC-archive/psammead#1356]
**Is your feature request related to a problem? Please describe.**
To enable LIV assets to be shown on our front pages, we need to be able to add a "LIVE" label before the headline text.

The label should not just be appended to the beginning of the headline, but rather be its own element because it's getting different typography.

**Describe the solution you'd like**
Add the ability to add a LIVE label to story promo. Maybe pass in a "isLive" prop, if yes, show the label. 

**Describe alternatives you've considered**
Honestly, no clue.
Making a separate component for the LIVE label, but that's just silly.

**Testing notes**
[Tester to complete]

Dev insight: Add a snapshot test to cover the scenario.

**Additional context**
WSFRONTPGS-81
[Designs + Accessibility](https://app.zeplin.io/project/5c8a5e021d454124ef90669f?seid=5d25bd8606494a2e258448cf
)

**Comment by greenc05** [comment]
Also note, accessibility acceptance criteria:

Given I use a screen reader
When I navigate to a live promo
And I am navigating via headings and links
Then the live label should be announced as part of the heading/link
And the live label should be announced first
 
Given I use a screen reader (LTR languages)
When viewing a live promo
The ‘Live’ label should be read in English, with an English accent
And it should be pronounced as ‘live’ as in ‘live event’ rather than ‘live’ as in ‘I live here’ 

Will add note later on how to achieve correct pronunciation (basically we need to add Live to the page twice, once for screen reader users and once for sighted users...)

**Comment by greenc05** [comment]
I haven't had time to fully test this, but we are looking at something like the code below to achieve (please note the use sentence case for the visually hidden element - this is important):

Given I use a screen reader (LTR languages)
When viewing a live promo
The ‘Live’ label should be read in English, with an English accent
And it should be pronounced as ‘live’ as in ‘live event’ rather than ‘live’ as in ‘I live here’

```
<h3>
	<a href=”">
		<span role="text">
			<span aria-hidden="true">LIVE</span>
			<span class="vis-hidden" lang="en-GB">Live, </span>
			<span>BBC Pidgin Minute</span>
		</span>
	</a>
</h3>
```
