### ISSUE TITLE
Add babel-plugin-styled-components to all packages

### ISSUE THREAD

**Issue by ChrisBAshton** [BBC-archive/psammead#159]
**Is your feature request related to a problem? Please describe.**
>You should definitely use the styled-components Babel plugin.

> While removing it doesn't break anything, it makes development a lot nicer by putting the component names into the generated classes, improves performance in production, and enables support for features like the css prop!

See https://github.com/BBC-News/psammead/pull/105#issuecomment-445263069 (thanks, @mxstbr!)

Not all of our packages use babel-plugin-styled-components. As a general rule, we should be adding it to all components (see #162). The components that don't use it will need updating so that they use it, and the snapshot tests will need updating as the class names will be different.

**Testing notes**
[Tester to complete]

Dev insight: Regression test only.

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by ryanmccombe** [comment]
This seems to have already been done: https://github.com/bbc/psammead/commit/fcea0b5f41b11c4e64fcba309f9f7d8a7437ece5

The issue talks about "adding it to all components" and "updating components that don't use it" - I'm not sure what that means in the context of a babel plugin?

It is configured in the `.babelrc` at the root of the directory, and is getting used by every styled component:

<img width="436" alt="Screen Shot 2019-06-17 at 11 13 15" src="https://user-images.githubusercontent.com/8601460/59597095-f3e60680-90f0-11e9-9a66-8fe4edcfd8bf.png">

This issue seems like it should be closed
