### ISSUE TITLE
Remove Enzyme tests - for now

### ISSUE THREAD

**Issue by ChrisBAshton** [BBC-archive/psammead#16]
We'll move the Headings component from Simorgh to Psammead in #12.

`Headings` has its own set of snapshot tests but is not tested with Enzyme. This is the case for all of the Simorgh components so far.

So that we are not held up on the component migration, let's port the snapshot tests over as-is. An investigation as to a better testing library will be happening in https://github.com/BBC-News/simorgh/issues/671, at which point we may update the component tests.

Rather than copy the component _and_ change the testing framework in one PR, this PR can handle removing Enzyme and the Enzyme tests.

**Comment by jtart** [comment]
@ChrisBAshton I think the migration of `enzyme` -> `react-test-renderer` feels like a bigger migration than `react-test-renderer snapshot APIs` -> `enzyme snapshot APIs`, and we would get benefits from being able to experiment with `enzyme` (when there is time). Based on these, would it be beneficial to keep `enzyme`?

**Comment by ChrisBAshton** [comment]
I think either way we'll be moving to Enzyme or React-Test-Renderer at some point, but the question around tests is slowing down our migration of components from Simorgh into Psammead. By keeping Enzyme, we either have to:

a) port the Headings tests over to Enzyme, or
b) configure the test environment to run both Enzyme and our shallow-render tests

...and we'd have to fix the tests which are currently broken (#25).

IMO we should kill Enzyme for now and perhaps resurrect it later.

**Comment by sareh** [comment]
Please note that currently Enzyme isn't even installed as a dependency, that's why it's broken in https://github.com/BBC-News/psammead/issues/25.  

I'd be happy to just remove the tests in the Example button file, since they're not being run. https://github.com/BBC-News/psammead/blob/latest/packages/example-button/src/index.spec.js

We can prioritise moving in the `Headings` component and get tests running for that component, rather than fix up the toy example `example-button`. We'll be removing this component very soon, anyway.

**Comment by jtart** [comment]
> b) configure the test environment to run both Enzyme and our shallow-render tests

Enzyme _does_ have (shallow) snapshot testing, but if it's not installed the easiest to just use `react-test-renderer`.

**Comment by dr3** [comment]
btw Enzyme is now installed due to https://github.com/BBC-News/psammead/pull/21
