### ISSUE TITLE
Stop building complex stories in psammead packages

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#2157]
**Is your feature request related to a problem? Please describe.**
In psammead we have a number of stories, like [story promo](https://github.com/bbc/psammead/blob/latest/packages/components/psammead-story-promo/src/index.stories.jsx) where we setup extremely complicated story designs.

This is just mimicking the layout in simorgh, IMO we should keep stories for psammead as simple as possible, just highlighting the bare bones components. Adding `VisuallyHiddenText`, `MediaIndicator` & `Timestamp` to the story of `Story Promo` gives a false representation of what the `story promo` component provides. 

**Describe the solution you'd like**
Slim down our existing stories, isolating them to only contain what they export. We should discuss if we should rely on Simorgh or a seperate collection of stories, to give a representation of what you _can_ build with psammead.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by ghost** [comment]
I think it is important that we decide on when we do accessibility checks for a component. If a component has a requirement for `VisuallyHiddenText` it makes sense to include that in the story in order to facilitate isolated accessibility checks on the component.

**Comment by DenisHdz** [comment]
I am happy simplifying them, as long as all the disciplines know that when something is missing in Psammead Storybook, they should check the Simorgh one to see all the functionality. 

Designers and a11y leads like to see them in Psammead during the development of a new component and also in conjunction with other ones, as happened with the navigation and the brand, which ends up adding all the requirements of a component in its story.

**Comment by sareh** [comment]
I think it's a visibility issue. Having a `storypromo - default` story that is *just* that promo, without media indicator etc, is very important. 

This component has props for four nodes - two required, `image` & `info`, two optional, `mediaIndicator` & `topStory`

The `storypromo - default` should include the simplest possible required nodes for `image` and `info` - a single image and a single text component - for example a heading or paragraph (`psammead-headings` or `psammead-paragraph`)

Then we should have clear additional examples that show how it'd look like with the extra nodes passed in:

```
storypromo - standard
storypromo - standard - with media indicatior
storypromo - top story
storypromo - top story - with media indicator
```

The examples should be the simplest possible. So for the `info` node, we shouldn't have a heading and paragraph and timestamp. 

In the `with media indicator` examples, we should use best practice with regards to accessibility - since users of the Psammead library can look to it as a usage example.

**Comment by samora** [comment]
I mostly agree with @sareh. However, I will keep `info`'s heading, paragraph and timestamp.

If we agree to keep best practices with regards to accessibility in stories, then it should be standardized across the project (I'm assuming it isn't).

**Comment by pjlee11** [comment]
IMO stories should: 
- be bespoke to the component we export
- show all permutations of the component based on the props, ideally in a dynamic way rather than static stories
  - EG: using knobs to control the value of the optional props 
- not contain complex usages 
  - EG: Timestamp should not be in StoryPromo stories
- give examples of correct a11y usage
  - EG: adding VisuallyHiddenText where appropriate

**Comment by dr3** [comment]
>give examples of correct a11y usage
>EG: adding VisuallyHiddenText where appropriate

Can you give an example of this please @pjlee11 

IMO stories should only contain what they export as _much_ as possible. We could perhaps have exceptions for when a package readme explictly states that you should use it with something for a11y

**Comment by pjlee11** [comment]
@dr3 without the a11y stories in psammead when would we perform a11y swarms before removing alpha from the component?  

An example would be something like [Copyright](https://github.com/bbc/psammead/tree/latest/packages/components/psammead-copyright) that has no props we would just export it as a styled text element. Without visually hidden text pre-fixing it the Copyright component doesn't make semantic sense in terms of the DOM but visually it seems sensible. 

We could potentially give an a11y usage example in the README rather than a story, but it should definitely be covered.

**Comment by samora** [comment]
From this thread it seems `Timestamp` is the only thing that should be removed. Everything can remain as is. There are already knobs setup for varying/optional props. I have updated the PR. Kindly review.
