### ISSUE TITLE
Add font-face declarations to Psammead

### ISSUE THREAD

**Issue by bcmn** [BBC-archive/psammead#284]
Blocked on https://github.com/bbc/psammead/issues/285

**Is your feature request related to a problem? Please describe.**
Currently, Psammead's font exports live in `psammead-styles` & make assumptions on font-face declarations being declared manually by any users of the exports.

**Describe the solution you'd like**
We should add the _full_ list of Reith variants as font-face declarations which are exported from a package. We should define these in a way that makes it easy to use custom-defined subsets of the full list, & that allows for switching between font styles as possible as possible.

[The font families currently defined in `psammead-styles`](https://github.com/bbc/psammead/blob/latest/packages/utilities/psammead-styles/src/fonts.js) are [defined by GEL](https://www.bbc.co.uk/gel/guidelines/typography#overview). They should live in `gel-foundations`.

We should determine the best way to reflect that all of these things are defined by GEL, & make this easy & helpful to use as generically as possible -- not just for the Simorgh/Psammead use case.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by dr3** [comment]
@bbc/article-devs-news Should we do this correctly before we transfer them? I.e. block this on the font investigation work?

The likely outcome of that investigation (based on my quick looking) will mean we export font-faces with a font-family of `ReithSansNews`, instead of all `ReithSansNewsRegular, ReithSansNewsBold, ReithSansNewsMedium, ReithSansNewsItalicMedium`

Could be strange to move them into a new package then immediately do a breaking change

**Comment by ChrisBAshton** [comment]
Is there a ticket for the font investigation work?

**Comment by dr3** [comment]
BLOCKED ON https://github.com/bbc/psammead/issues/285

**Comment by bcmn** [comment]
Closing as covered by #285.
