### ISSUE TITLE
Animation for navigation dropdown not working on IOS

### ISSUE THREAD

**Issue by OlgaLyubin** [BBC-archive/psammead#2898]
**Describe the bug**
Currently, animation of a dropdown menu does not work on IOS (clicking on the hamburger button does not show the menu).
To see the bug you need to check Simorgh integration of new navigation, but the bug is most probably a Psammead issue.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to any service frontPage with integrated navigation
2. Click on the hamburger menu button
3. See error

**Expected behaviour**
A dropdown menu slides down with animation when you click on the menu button.

**Smartphone (please complete the following information):**
- Device: iPhone
- OS: 12 and 13
- Browser: Safari

**Testing notes**
- [x] This bug fix is expected to need manual testing.

**Comment by AlistairGempf** [comment]
Following investigation, we think the problem is not with any of the code, but with client-side javascript. Since the button requires client-side javascript, if this doesn't load then the button doesn't work. The easiest way to tell if it has loaded is to scroll down a little bit and check if the 'lazy loaded' images for non-top stories are loading. If they are then the client-side js is loaded, otherwise it's not.

We think the reason the client-side js is not loading on iOS is that `localhost` cannot be loaded on iOS, so no matter how the the page is loaded, the `host` header is never the expected value of `localhost` so it cannot load the client-side js. BrowserStack gets around this by redirecting `bs-local.com` to your `localhost` but this will again cause the `host` header to be `bs-local.com` rather than the expected `localhost`.

Further evidence of the js not loading is looking at the development tools by connecting an iPhone via USB cable, the button has no event-handlers attached to it.

I have tested by editing the webpack config to serve from the hostname I can access from my iPhone connected by USB and the button works with animations.
