### ISSUE TITLE
Odd spacing in first item of Korean due to thin font glyph

### ISSUE THREAD

**Issue by hotinglok** [BBC-archive/psammead#2949]
**Describe the bug**
On the first item in MostRead in Korean, the font/glyph for the number "1" is much thinner than other fonts which leads to the link being shifted in/not consistent with any other link in the same column.

**To Reproduce**
Steps to reproduce the behaviour:
1. This only affects modern browsers (somehow).
2. Go to storybook either on `localhost` or at bbc.github.io/psammead.
3. Go to MostRead, `defaultLTR`.
4. Select Korean in the service knob and see error.

**Expected behaviour**
First item should be consistent with all other items.

**Screenshots**
Not working in chrome:
![image](https://user-images.githubusercontent.com/53564281/72605295-6a134b80-3914-11ea-99cf-0f89b9fa5ce4.png)

More obvious shot with text in English on bbc.github.io/psammead:
![image](https://user-images.githubusercontent.com/53564281/72605730-3c7ad200-3915-11ea-8cb7-3577a3f459a6.png)

~Miraculously~ working in IE: 
![image](https://user-images.githubusercontent.com/53564281/72605611-09384300-3915-11ea-98b0-2eab25f3b078.png)

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Comment by hotinglok** [comment]
Marking as low priority for now due to prioritising getting MostRead pulled into simorgh.

**Comment by mmcculloch** [comment]
I've had a brief look into this. The issue comes from `min-width: auto` for single digit https://github.com/bbc/psammead/blob/latest/packages/components/psammead-most-read/src/Rank/index.jsx#L48

It can be partially fixed by setting it to a fixed value, e.g `4rem`, but this probably alters UX intentions and it's difficult to verify all languages and breakpoints are issue free. I feel like it might not be worth implementing a fix for this one edge case.

**Comment by hotinglok** [comment]
Closing due to being encompassed by https://github.com/bbc/psammead/issues/3103
