### ISSUE TITLE
Radio Schedule duration is formatted differently on server render vs client render

### ISSUE THREAD

**Issue by tochwill** [BBC-archive/psammead#3373]
**Describe the bug**
The server rendered duration in the radio schedule section does not respect the service locale, whereas the client rendered duration does. As we do not currently set the locale when formatting the duration timestamp, this is probably due to some other code running on the client updating the global moment locale.

We can update the `formatDuration` function in `psammead-timestamp-container` to accept the locale as an argument, and then ensure the local moment locale is set:

```
return moment.utc(durationInMilliseconds).format(format);
```

becomes
```
return moment.utc(durationInMilliseconds).locale(locale).format(format)
```

Check how this affects the work being done as part of https://github.com/bbc/psammead/issues/3358.

Another point to note is that the `,` delimiter that has been used to format the visually hidden duration is not respected for all locales - it is replaced with a `.` for example on the afrique site, or `،` for persian. We can check this for all services - `,` may not be a valid character for this script so we should be careful about forcing this behaviour, and let moment format these in a way that is better suited (we can check the screen reader output). Is a separate visually hidden timestamp the right approach?

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to the persian homepage: localhost:7080/persian
2. View radio schedules section
4. You will see the numerals rendered with western arabic numerals on the server, which then change to the service numerals on the client.

**Expected behaviour**
The server render of the duration timestamp should respect the locale settings, and match the client render.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

**Comment by greenc05** [comment]
"Another point to note is that the , delimiter that has been used to format the visually hidden duration is not respected for all locales - it is replaced with a . for example on the afrique site, or ، for persian. We can check this for all services - , may not be a valid character for this script so we should be careful about forcing this behaviour, and let moment format these in a way that is better suited (we can check the screen reader output). Is a separate visually hidden timestamp the right approach?" 

Thanks for raising this, to my knowledge the comma delimiter has not been fully considered for non latin based languages, as you point out. Adding a comma delimiter was a compromise solution for latin based languages to the ideal VH UX that was desired such as "1 minute 2 seconds" to somewhat mitigate screen readers interpreting 1:02 as a timestamp rather than a duration. We prefix the label 'duration' in this component, which gives context, so perhaps somewhat mitigates the need for a comma delimiter in this situation... (Note UX where happy to also add the label 'duration' to media promos...) I would recommend that before considering removing the comma delimiter, that we should test a range of durations with the prefix label 'duration' with all our supported AT for UX to consider.

**Comment by tochwill** [comment]
We will keep track of the work being done by @sareh and perform another a11y swarm to check this and see if we need to do anything else on top of this work.

**Comment by tochwill** [comment]
Blocked on #3358

**Comment by sareh** [comment]
Should be opened until we pull in `@bbc/psammead-timestamp-container` version 3.0.0 into the Radio Schedule.

**Comment by EinsteinNjoroge** [comment]
Closing this since Radio Schedule is now using version 3.0.0 of @bbc/psammead-timestamp-container. https://github.com/bbc/psammead/blob/669bf6ecf65a38372cd78ca259640b60081786fb/packages/components/psammead-radio-schedule/package.json#L26.
cc @sareh
