### ISSUE TITLE
Radio bulletin - No summary in paragraph element on arabic

### ISSUE THREAD

**Issue by greenc05** [BBC-archive/psammead#3429]
**Describe the bug**
The radio bulletin on https://www.bbc.com/arabic has a empty paragraph element without any summary text.

**Expected behaviour**
A summary should be rendered in the paragraph element. If this cannot happen then no paragraph element should be rendered. 

**Screenshots**
<img width="592" alt="Screen Shot 2020-04-27 at 14 45 56" src="https://user-images.githubusercontent.com/1061401/80379891-9d139680-8896-11ea-9d4e-a59a2c05d911.png">

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

**Comment by sareh** [comment]
@greenc05 Thank you for raising this. 
Your screenshot shows another issue - in that we shouldn't render an empty paragraph element in the case where there is no summary data.

In terms of the case about the heading [Radio Schedule Program Card](https://github.com/bbc/psammead/blob/latest/packages/components/psammead-radio-schedule/src/ProgramCard/index.jsx). 
Looking at the whole card's content here, we see that the heading `<h3>` and summary `<p>`are in one div with the duration `<time><span>` for visually hidden text in a different div. I'd think it would be useful to see if it is possible to update the DOM structure to have the h3 heading be in the same node as the duration element. I think this would be useful to screenreader users since the duration would be associated with the heading level three, instead of appear to be two separate elements.

<img width="803" alt="Screenshot of Programme card" src="https://user-images.githubusercontent.com/3028997/80384224-85d7a780-889c-11ea-9954-ef63735b1553.png">

I'd be interested in hearing your view on this.

**Comment by greenc05** [comment]
Note this issue has been edited. It did say the h3 in the component should be swapped for a div as content should follow a heading, if there is no summary text. This is actually not a good solution in context of the larger component/page section. As this content/promo would then sit under the heading of the promo before it...
