### ISSUE TITLE
Images and Text should have 24px padding above & below

### ISSUE THREAD

**Issue by ChrisBAshton** [BBC-archive/psammead#379]
**Is your feature request related to a problem? Please describe.**
Issue raised by Natalie (UX). Our Text and Image blocks should have 24px of padding above & below. Not clear if that means 12px in reality (12px padding-bottom from first block, plus 12px padding-top from second block).

"Needs an extra 8px".

**Describe the solution you'd like**
A PR to increase the padding as per designs. 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Snapshots need updating. Work with UX to review the designs in storybook once updated.

**Additional context**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by pjlee11** [comment]
We had previously agreed with UX that components would dictate the padding below themselves rather than both above and below. This is because it would require components to have knowledge of what is before/after them and will greatly increase the styling rules when working with an infinitely flexible CMS.

Current scenario:
```
|--------|
|  Text  |
|  16px  |
|--------|
| Image  |
|  16px  |
|--------|
|  Text  |
|  16px  |
```

Because of this, we agreed with UX on a 16px base spacing below each component. Realistically we should implement this issue as an increase in the padding bottom from 16px to 24px. 

Suggested change:
```
|--------|
|  Text  |
|  24px  |
|--------|
| Image  |
|  24px  |
|--------|
|  Text  |
|  24px  |
```
