### ISSUE TITLE
Support italicised text in Captions

### ISSUE THREAD

**Issue by ChrisBAshton** [BBC-archive/psammead#416]
**Is your feature request related to a problem? Please describe.**
Our captions are _italic text_ by default. But journalists have the option to mark up captions as italic in Optimo. In this case, we want to render the text without italics (i.e. italic and non-italic text get flipped).

Expected input:

`This is my <em>caption</em>`

Expected output:

> _This is my_ caption 

**Describe the solution you'd like**
Some CSS to support italicised text (but using 'normal' rather than 'italic'). E.g.

```css
figcaption {
  font-style: italic;
  em {
    font-style: normal;
  }
}
```

Psammead Caption styles should be updated:
https://github.com/bbc/psammead/blob/latest/packages/components/psammead-caption/src/index.jsx
Should be a minor version bump.

After the Psammead changes have been merged, we should open a PR to use this updated version in Simorgh. 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Storybook & snapshot tests required.

**Additional context**
Note that this functionality is similar to what is needed for Persian (#376).

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by twinlensreflex** [comment]
![Screen Shot 2019-04-16 at 08 27 12](https://user-images.githubusercontent.com/19362408/56190218-a92d0d00-6021-11e9-9db1-d8316be9917e.png)
This is the rendering of some data that I added to Simorgh storybook tests as part of #1585 (in simorgh)
The data has italic text and in the rendered content it's coming through as `<i>` rather than `<em>`. I'm guessing that's the expected behaviour and the code snippet in this ticket should read
```
figcaption {
  font-style: italic;
  i {
    font-style: normal;
  }
}
```
instead.
