### ISSUE TITLE
Create prop types shape for typography scripts

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#425]
**Is your feature request related to a problem? Please describe.**
We should be more restrictive about what 'object' we allow

Current:
```
SubHeading.propTypes = {
  script: objectOf(object).required,
};
```

**Describe the solution you'd like**
Following the [articles example](https://github.com/bbc/simorgh/blob/latest/src/app/containers/Article/index.jsx#L64), export a proptypes shape to use in downstream components

Desired:

```
SubHeading.propTypes = {
  script: objectOf(scriptPropTypes).required,
};
```

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: When run locally, you dont get a prop type warning.

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by DenisHdz** [comment]
@dr3 
At the moment the components require to pass the `script` prop but they are not using any default when not.

Should we then use `propTypes` instead of `defaultProps` as follows?

`Headline.propTypes = {
  script: objectOf(scriptPropTypes).isRequired,
};`
`SubHeading.propTypes = {
  script: objectOf(scriptPropTypes).isRequired,
};`

**Comment by dr3** [comment]
Ahh yes, well spotted @DenisBBC, I copied the wrong snippet, updated :)
