### ISSUE TITLE
Media indicator above promo when 360px or over

### ISSUE THREAD

**Issue by DenisHdz** [BBC-archive/psammead#726]
**Is your feature request related to a problem? Please describe.**
UX requested to display the `mediaIndicator` above the promo image when we hit `360px` instead of `400px`.

**Describe the solution you'd like**
Replace [400px](https://github.com/bbc/psammead/blob/19abbced584253b93ea27a60d4f6f77a03cb1d79/packages/components/psammead-story-promo/src/index.jsx#L122) breakpoint with 360px.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by amywalkerdev** [comment]
Discussed with Laura and Clare, we should have breakpoints for 240, 360 and 400 in WS and not just the lowest 400 GEL one. The Articles UX team will also be following this approach for WS article designs so it will be a Simorgh standard

**Comment by dr3** [comment]
Blocked on https://github.com/bbc/psammead/issues/744

**Comment by sareh** [comment]
@amywalker1987 In our component library we currently have GEL groups(breakpoints)  1-5, plus we have added an added one - Group 0, (240px) for the usecase of feature phones.

What is being suggested here is a group in-between 0 and 1, at 360px.

Could it please be stated why this extra breakpoint is needed - i.e. which devices require a specific breakpoint between 240px & 400px, including their percentage user base of each of the World Service sites.

The addition of an extra breakpoint should have the relevant stats. 

Once this need is stated, and clarified, then as devs and designers, we should discuss whether the stats support the necessity of adding an additional breakpoint at 360px.

Only at the point where this is agreed, can we discuss the practicalities of naming and adding a group in the library, because `GROUP_0POINT5` is likely unhelpful. We would need to change the naming of `GROUP_0` for 240px.
This would be a breaking change to the `@bbc/gel-foundations` library.

The reasons for these steps needing to be taken is that our breakpoints in our library are our fundamental base for all of our shared components. 

If the 360px media query is urgently needed for the front pages launch and the existing 240px and 400px are not considered sufficient at all by the UX team, we can discuss this more urgently. 

But I strongly suggest that for this particular issue, one of the two breakpoints 240px or 400px be used.

**Comment by amywalkerdev** [comment]
Closing this as per Clare's comments on #744
