### ISSUE TITLE
Build packages for publish

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#73]
**Describe the bug**
Currently our packages are ES6 when published and thus have issues when pulling them into simorgh as it doesnt run node modules through babel.

**To Reproduce**

1. Import @bbc/psammead-styles into simorgh
2. See error `Unexpected Token Export`

**Expected behavior**
The module should import correctly

**Solutions**
- Build them pre-publish
- Whitelist the packages in simorgh node modules to be babel-ified

- [x] Initially labelled with ["refinement-needed"](https://github.com/BBC-News/psammead/labels/refinement-needed)

**Comment by ChrisBAshton** [comment]
Just had a look at component libs investigated in https://github.com/BBC-News/simorgh/issues/972 and not one of them offers a `build`/`dist` version for ES5, as far as I can see.

So I'd strongly suggest fixing the transpilation issue in Simorgh rather than offering ES5 versions of our components.

* [Atlaskit](https://bitbucket.org/atlassian/atlaskit-mk-2/src/4d29ec4baaff6040935ca6a07a83f3692538310b/packages/media/media-card/?at=master)
* [react-bootstrap](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Alert.js)
* [grommet](https://github.com/grommet/grommet/tree/master/src/js/components/Anchor)
* [material-ui](https://github.com/mui-org/material-ui/blob/master/packages/material-ui-lab/src/Slider/Slider.js)
* [reach-ui](https://github.com/reach/reach-ui/blob/master/packages/dialog/src/index.js)
* [blueprint](https://github.com/palantir/blueprint/blob/develop/packages/core/src/index.ts)
* [Ant](https://github.com/ant-design/ant-design/blob/master/components/anchor/index.tsx)

**Comment by ChrisBAshton** [comment]
Actually I just had a major gap in my knowledge - turns out most packages will run a `prepublish` script to offer an ES2015 version: https://stackoverflow.com/questions/29738381/how-to-publish-a-module-written-in-es6-to-npm

http://krasimirtsonev.com/blog/article/javascript-library-starter-using-webpack-es6

https://hackernoon.com/how-to-publish-your-package-on-npm-7fc1f5aae600

So in hindsight - yes we probably need to do this!
