### ISSUE TITLE
Add 360px Breakpoint

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#744]
Discussed with Laura and Clare, we should have breakpoints for 240, 360 and 400 in WS and not just the lowest 400 GEL one. The Articles UX team will also be following this approach for WS article designs so it will be a Simorgh standard

_Originally posted by @amywalker1987 in https://github.com/bbc/psammead/issues/726#issuecomment-507346728_

**Describe the solution you'd like**
Add a 360px breakpoint

**Describe alternatives you've considered**
Sticking to 400px

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by dr3** [comment]
So are we saying the breakpoints will be `240, 360, 400, 600, 1008, 1280`?

Do we have any data to reflect the need for a 360 breakpoint? Re: number of devices?

What will use 360 vs 400?

**Comment by pjlee11** [comment]
What is the significant difference between 360px and 400px? Could we potentially lower the 400 breakpoint to 360? 
Feels like a very similar experience within that 40px difference and the added complexity for dev could out-weigh the user benefit depending on the reason/significance

**Comment by pjlee11** [comment]
Also this could be an example of how we should be tracking the user's device width to ensure the breakpoints match real devices in the wild. Only internal staff will shrink a browser to 372px's to check the layout meaning real data would be better to skew our decisions

**Comment by dr3** [comment]
This would require moving breakpoints out of [@bbc/gel-foundations](https://github.com/bbc/psammead/blob/latest/packages/utilities/gel-foundations/src/breakpoints.js) as they wont meet the GEL spec anymore

**Comment by sareh** [comment]
I replied here regarding my views on this suggested change: https://github.com/bbc/psammead/issues/726#issuecomment-507353640

**Comment by clareevansbbc** [comment]
Thanks for all your input on this question - Laura and I will have an answer for you on what we will do for v1 by the end of today.

**Comment by clareevansbbc** [comment]
Here's a summary of the thinking and the plan for going forward, **TL;DR: no change required - stick with the current behaviour of the media indicator** 

Existing GEL breakpoints:  400, 600, 1008, 1280
Existing Simorgh breakpoints:  240, 400, 600, 1008, 1280

Issue: 
The media indicator in the story promo requires different behaviour depending on the screen width, due to the indicator covering the majority of the promo image. It was proposed we add new breakpoint at 360px which is when the promo image is big enough for the indicator to sit comfortably over it. 

There are 2 behaviours for regular story promos (NOT the main top story):
- the indicator covers the image in the bottom left corner
- the indicator sits directly beneath the image, aligned on the left of the image

For V1 we will NOT add the new 360px breakpoint, we will go with the following behaviour at the existing breakpoints:
- 400px and above: the indicator covers the image
- 399px and below: the indicator sits below the image

We will likely revisit this in the future to improve the behaviour for smaller devices.
