### ISSUE TITLE
Consider package naming convention

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#9]
**Is your feature request related to a problem? Please describe.**
Have a defined package naming convention for component packages.

**Describe the solution you'd like**
All packages have a standard prefix suchs `bbc-psammead-`, `psammead-` etc. This will avoid issues with name clashing a vagueness such as in the case of example button https://www.npmjs.com/package/example-button

**Comment by ChrisBAshton** [comment]
For now, we have the `@bbc` namespace which can be private or public. In the future, we may have team-based ones, eg `@iplayer`, but this is pending our move to NPM Enterprise. Either way, we will have a BBC namespace outside of the immediate package name.

Current:

1. `@bbc/psammead-headings` org-level namespace, team-level prefix, component name
2. `@bbc/psammead-component-headings` org-level namespace, team-level prefix, component 'category', component name
2. `@bbc/gel-component-headings` org-level namespace, OPR-friendly component prefix, component name

...or (in the future) any of the above but with a team name e.g. `@psammead`, in which case we'd probably want to avoid doing `@psammead/psammead-headings`.

I'd be in favour of option 1, and we can always migrate to a different org prefix in the future. Option 1 is relatively OPR-friendly insofar as it isn't tied to a specific product/brand, and I don't think a 'component'-like prefix is necessary since Psammead is _all_ about components.

**Comment by dr3** [comment]
+1 for option 1

**Comment by ChrisBAshton** [comment]
This is now captured in https://github.com/BBC-News/psammead/issues/36#issuecomment-441568971.
